license="Apache-2.0"
[[mods]]
modId="${id}"
version="${version}"
displayName="EasyBot NeoForge"
logoFile = "assets/${id}/logo.png"
authors = "MiuxuE"
description = "EasyBot for NeoForge"
[[mixin]]
config="easybot.mixins.json"

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge},)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_range}"
ordering="NONE"
side="SERVER"