modLoader = "javafml"
gameLoader = "neoforge"
loaderVersion = "[1,)"
license = "Apache-2.0"
issueTrackerURL = "https://github.com/easybot-team/easybot-mod/issues"
[[mods]]
modId = "${id}"
version = "${version}"
displayName = "EasyBot NeoForge"
logoFile = "assets/${id}/logo.png"
authors = "MiuxuE"
description = "EasyBot for NeoForge"
[[mixin]]
config = "easybot.mixins.json"

[[dependencies.${ id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.${ id }]]
modId = "geyser_neoforge"
type = "optional"
versionRange = "[2.2.0-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ id }]]
modId = "floodgate"
type = "optional"
versionRange = "[2.2.0-SNAPSHOT,)"
ordering = "NONE"
side = "BOTH"